DROP DATABASE proyecto;

CREATE DATABASE proyecto;
USE proyecto;
CREATE TABLE datos
(id    INTEGER AUTO_INCREMENT NOT NULL,
nombre VARCHAR(255) NOT NULL,
edad INTEGER NOT NULL,
correo VARCHAR(255) NOT NULL,
PRIMARY KEY (id));